# Generated by Django 4.0.3 on 2022-05-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programmes_Offered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(choices=[('Hospitality', 'Hospitality'), ('Computing', 'Computing'), ('Business', 'Business')], default='Hospitality', max_length=50)),
                ('programme_name', models.TextField(max_length=200)),
                ('programme_duration', models.CharField(default='1 year', max_length=200)),
                ('Intake_from', models.DateField()),
                ('Intake_to', models.DateField()),
                ('optional_examinational_body', models.TextField(default='ICDL', max_length=200)),
                ('examination_body', models.CharField(choices=[('KNEC', 'KNEC'), ('KASNEB', 'KASNEB'), ('NITA', 'NITA'), ('ICDL', 'ICDL')], default=models.TextField(default='ICDL', max_length=200), max_length=50)),
            ],
        ),
    ]
