# Generated by Django 4.0.3 on 2022-05-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0004_alter_programmes_offered_examination_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmes_offered',
            name='optional_examinational_body',
        ),
        migrations.AlterField(
            model_name='programmes_offered',
            name='examination_body',
            field=models.CharField(choices=[('KNEC', 'KNEC'), ('KASNEB', 'KASNEB'), ('NITA', 'NITA'), ('ICDL', 'ICDL'), ('East Technical Institute', 'East Technical Institute')], default='East Technical Institute', max_length=50),
        ),
    ]
