# Generated by Django 4.0.3 on 2022-05-15 10:32

from django.db import migrations, models
import programmes.models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0005_remove_programmes_offered_optional_examinational_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmes_offered',
            name='Intake_from',
            field=models.DateField(validators=[programmes.models.Programmes_Offered.validate_year]),
        ),
        migrations.AlterField(
            model_name='programmes_offered',
            name='Intake_to',
            field=models.DateField(validators=[programmes.models.Programmes_Offered.validate_year]),
        ),
    ]
