# Generated by Django 4.0.3 on 2022-05-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0006_alter_programmes_offered_intake_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmes_offered',
            name='programme_requirements',
            field=models.TextField(default='KCSE Grade C', max_length=200),
        ),
        migrations.AlterField(
            model_name='programmes_offered',
            name='Intake_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='programmes_offered',
            name='Intake_to',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='programmes_offered',
            name='programme_name',
            field=models.CharField(max_length=250),
        ),
    ]
