# Generated by Django 4.0.3 on 2022-05-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0008_programmes_offered_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme_Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(choices=[('Hospitality', 'Hospitality'), ('Computing', 'Computing'), ('Business', 'Business')], default='Hospitality', max_length=50)),
                ('programme_name', models.CharField(max_length=250)),
                ('programme_duration', models.CharField(default='1 year', max_length=200)),
                ('programme_requirements', models.TextField(default='KCSE Grade C', max_length=200)),
                ('Intake_from', models.DateField()),
                ('Intake_to', models.DateField()),
                ('examination_body', models.CharField(choices=[('KNEC', 'KNEC'), ('KASNEB', 'KASNEB'), ('NITA', 'NITA'), ('ICDL', 'ICDL'), ('East Technical Institute', 'East Technical Institute')], default='East Technical Institute', max_length=50)),
                ('vacancy', models.BooleanField(default=False)),
            ],
        ),
    ]
