# Generated by Django 4.0.3 on 2022-05-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0009_programme_intake'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Programme_Intake',
        ),
    ]
