# Generated by Django 4.0.3 on 2022-05-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0010_delete_programme_intake'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmes_offered',
            name='apply_button',
            field=models.CharField(default='Apply', max_length=200),
        ),
    ]
