# Generated by Django 4.0.4 on 2022-05-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0011_programmes_offered_apply_button'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_first_name', models.CharField(max_length=50)),
                ('applicant_middle_name', models.CharField(max_length=50)),
                ('applicant_last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('dob', models.DateField()),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced'), ('Other', 'Other')], max_length=8)),
                ('religion', models.CharField(choices=[('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Hindu', 'Hindu'), ('None Religion', 'None Religion')], max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('idno', models.PositiveIntegerField()),
                ('mobile_number', models.PositiveIntegerField()),
                ('home_district', models.CharField(max_length=50)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('postal_address', models.PositiveIntegerField()),
                ('postal_code', models.PositiveIntegerField()),
                ('town', models.CharField(max_length=50)),
                ('county', models.CharField(choices=[('Mombasa', 'Mombasa')], max_length=50)),
                ('applicant_parent', models.CharField(max_length=50)),
                ('applicant_parent_number', models.PositiveIntegerField()),
                ('course_applied', models.CharField(max_length=50)),
            ],
        ),
    ]
