# Generated by Django 4.0.3 on 2022-04-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customize_home_page',
            name='ETC_mail',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customize_home_page',
            name='ETC_phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customize_home_page',
            name='carousel_button',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customize_home_page',
            name='carousel_message',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customize_home_page',
            name='carousel_second_message',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customize_home_page',
            name='home_carousel_pics',
            field=models.ImageField(default=1, upload_to='Site Carousels'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customize_home_page',
            name='office_venue',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customize_home_page',
            name='opening_time',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customize_home_page',
            name='school_logo',
            field=models.ImageField(default=1, upload_to='Site Images'),
            preserve_default=False,
        ),
    ]
