# Generated by Django 4.0.3 on 2022-05-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_customize_home_page_certificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customize_home_page_gallery_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_level', models.CharField(choices=[('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Degree', 'Degree')], default='Certificate', max_length=50)),
                ('level', models.CharField(choices=[('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Degree', 'Degree')], default='Certificate', max_length=50)),
                ('gallery_pics', models.ImageField(default='easttech logo.jfif', upload_to='Site Gallery')),
            ],
        ),
        migrations.RemoveField(
            model_name='customize_home_page',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='customize_home_page',
            name='diploma',
        ),
    ]
