# Generated by Django 4.0.3 on 2022-05-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_customize_home_page_gallery_courses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customize_study_with_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_second_message', models.CharField(default='Join us Now', max_length=200)),
                ('carousel_button', models.CharField(default='Apply', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='customize_home_page_gallery_courses',
            name='level',
        ),
        migrations.AddField(
            model_name='customize_home_page_gallery_courses',
            name='button_text',
            field=models.CharField(default='Apply now', max_length=50),
        ),
        migrations.AddField(
            model_name='customize_home_page_gallery_courses',
            name='course',
            field=models.CharField(default='In Hospitality', max_length=50),
        ),
        migrations.AddField(
            model_name='customize_home_page_gallery_courses',
            name='duration',
            field=models.DurationField(default='1 year'),
        ),
        migrations.AddField(
            model_name='customize_home_page_gallery_courses',
            name='edu_school',
            field=models.CharField(choices=[('Hospitality', 'Hospitality'), ('Computing', 'Computing'), ('Business', 'Business')], default='Hospitality', max_length=50),
        ),
    ]
