# Generated by Django 4.0.3 on 2022-05-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_customize_study_with_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customize_home_page_gallery_courses',
            name='duration',
            field=models.DurationField(default=365),
        ),
    ]
