# Generated by Django 4.0.3 on 2022-05-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0007_alter_customize_home_page_gallery_courses_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customize_home_page_gallery_courses',
            name='duration',
            field=models.DurationField(default=365, verbose_name='day'),
        ),
    ]
