# Generated by Django 4.0.3 on 2022-05-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0008_alter_customize_home_page_gallery_courses_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customize_home_page_gallery_courses',
            name='duration',
            field=models.CharField(default='1 year', max_length=10),
        ),
    ]
