# Generated by Django 4.0.3 on 2022-05-01 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0009_alter_customize_home_page_gallery_courses_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customize_home_page_gallery_courses',
            old_name='duration',
            new_name='course_duration',
        ),
    ]
