# Generated by Django 4.0.3 on 2022-05-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0011_remove_customize_study_with_section_carousel_button_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='myCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_message', models.CharField(default='Value Added Education', max_length=200)),
                ('carousel_second_message', models.CharField(default='Join us Now', max_length=200)),
                ('carousel_button', models.CharField(default='Apply', max_length=20)),
                ('home_carousel_pics', models.ImageField(default='easttech logo.jfif', upload_to='Site Carousels')),
            ],
        ),
        migrations.RemoveField(
            model_name='customize_home_page',
            name='carousel_button',
        ),
        migrations.RemoveField(
            model_name='customize_home_page',
            name='carousel_message',
        ),
        migrations.RemoveField(
            model_name='customize_home_page',
            name='carousel_second_message',
        ),
        migrations.RemoveField(
            model_name='customize_home_page',
            name='edu_level',
        ),
        migrations.RemoveField(
            model_name='customize_home_page',
            name='home_carousel_pics',
        ),
        migrations.AlterField(
            model_name='customize_home_page',
            name='school_logo',
            field=models.ImageField(default='easttech logo.jfif', upload_to='Site Images'),
        ),
    ]
