# Generated by Django 4.0.3 on 2022-05-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0012_mycarousel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customize_home_page_gallery_courses',
            name='course',
            field=models.TextField(default='Hotel Management', max_length=200),
        ),
    ]
