# Generated by Django 4.0.3 on 2022-05-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0014_customize_home_page_gallery_courses_course_require'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_From_Principle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Incharge_pic', models.ImageField(default='easttech logo.jfif', upload_to='In charge')),
                ('Incharge_name', models.CharField(default='PRINCIPAL', max_length=50)),
                ('designation', models.TextField(default='Welcome to East Technical College', max_length=600)),
            ],
        ),
    ]
