# Generated by Django 4.0.3 on 2022-05-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0017_rename_incharge_designation_message_from_principle_incharge_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_from_principle',
            name='message_title',
            field=models.TextField(default='Welcome to East Technical College', max_length=600),
        ),
    ]
