# Generated by Django 4.0.3 on 2022-05-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0018_message_from_principle_message_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_from_principle',
            name='message_title',
            field=models.CharField(default='Welcome to East Technical College', max_length=200),
        ),
    ]
