# Generated by Django 4.0.3 on 2022-05-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0020_message_from_alumni'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_ETC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_gallery_pic', models.ImageField(default='easttech logo.jfif', upload_to='About us')),
                ('About_title', models.CharField(default='Business Manager', max_length=50)),
                ('About_pic', models.ImageField(default='easttech logo.jfif', upload_to='About us')),
                ('About_message', models.TextField(default='East Technical College is the place to be', max_length=600)),
            ],
        ),
    ]
