# Generated by Django 4.0.3 on 2022-05-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0021_about_etc'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_etc',
            name='About_update',
            field=models.CharField(default='4 hours', max_length=50),
        ),
    ]
