# Generated by Django 4.0.3 on 2022-05-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0022_about_etc_about_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_etc',
            name='About_title',
            field=models.CharField(default='ABOUT EAST TECHNICAL COLLEGE', max_length=50),
        ),
    ]
